server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/php?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abc123456
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8

  resources:
    static-locations: classpath:static/

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.java.springboot.bean

logging:
  level:
    com:
      example:
        mapper : debug

